### ISSUE TITLE
webapp name in section 6.5 is incorrect

### ISSUE THREAD

**Issue by jamesfalkner** [CloudLabsAI-Azure/workshop-migrate-jboss-on-app-service#2]
This section has `-n "${WEBAPP_NAME}"` but it should be `-n "${ASE_WEBAPP_NAME}"`

![image](https://user-images.githubusercontent.com/861894/161829848-f2a14f7e-3225-4f03-851b-fce29af2b1fc.png)

**Comment by AdarshRazor** [comment]
Changed the value
