### ISSUE TITLE
section 1.2.1: instructions rendered poorly

### ISSUE THREAD

**Issue by jamesfalkner** [CloudLabsAI-Azure/workshop-migrate-jboss-on-app-service#3]
![Screen Shot 2022-05-09 at 11 15 21 AM](https://user-images.githubusercontent.com/861894/167441899-579eaedf-f016-4d05-9bc5-d0722a8a9028.png)

See error above in markdown

**Comment by AdarshRazor** [comment]
Fixed the issue. Now the code is rendering properly.
